replicaCount: 3

image:
  repository: ghcr.io/surajm2021/realtime-event-gateway
  pullPolicy: IfNotPresent
  tag: "v0.1.0"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75

service:
  type: ClusterIP
  port: 80
